### PR TITLE
Pass arguments to request for clicks_summary

### PR DESCRIPTION
**Pull request by CodingFu**

### CODE REVIEW

**Comment by CodingFu** [comment]
Hi there. I've just noticed that you always pass `nil` for all the clicks_summary params and created a PR for you to fix it.

**Comment by philnash** [comment]
Oops, that's a mistake! Thanks for spotting it. Will get this merged in soon.

**Comment by philnash** [comment]
Ok, that's merged and released as [v2.0.1](https://rubygems.org/gems/bitly/versions/2.0.1). Thanks again!

**Comment by CodingFu** [comment]
thank you!

**Pull request merged**
