### PR TITLE
Add optional state param to OAuth2 authorize_url

### PR DESCRIPTION
**Pull request by jfiorato**
Adding the optional `state` parameter that is documented [here](http://dev.bitly.com/authentication.html) to the `authorize_url` method.

### CODE REVIEW

**Comment by philnash** [comment]
Hey, that looks good, thanks! Can I ask why `activesupport` was added to the development dependencies in the gemspec though?

**Comment by jfiorato** [comment]
@philnash Short answer is that the `shoulda` gemspec results in a bundle of incompatible gems.

Long answer is:
`shoulda` depends on `shoulda-matchers`, which in turn depends `active-support >= 3.0.0`

`active-support 4.2` depends on `minitest ~> 5.1`

`minitest 5.1` is incompatible with `test-unit`, in which `shoulda-context-1.2.1` depends on.

`shoulda` also depends on `shoulda-context`

Someone in there should update their gemspec, but not exactly sure who.

**Comment by philnash** [comment]
@jfiorato That... makes a lot of sense! I had trouble with shoulda and minitest when upgrading Rails apps a while back. I will get this merged.

**Comment by philnash** [comment]
Ok, this is available in the latest version 0.10.4

**Pull request merged**
