### PR TITLE
Support oauth 2.1

### PR DESCRIPTION
**Pull request by ollym**

### CODE REVIEW

**Comment by philnash** [comment]
Thanks for this @ollym! I'll find some time to check that the breaking changes from v1 to v2 of oauth2 don't cause us any trouble here. Though the tests all passed, which is certainly a good sign!

**Comment by ollym** [comment]
Thanks @philnash yea we didn't have an issues with our internal tests either, this one's important for us as it's creating a conflict with another gem that also depends on `oauth2` which has now moved onto v2.

Anything I can help you with?

**Comment by philnash** [comment]
I went through the Changelog for oauth2 and nothing looked out of place for this usage. The tests all run and your internal tests worked, so I am satisfied this is not going to break here.

I've merged and will get a release out now.

**Comment by philnash** [comment]
[Version 2.0.2 is released](https://rubygems.org/gems/bitly/versions/2.0.2)! Thanks for this update @ollym and for using the gem. Let me know if there's anything else I can help with.

**Pull request merged**
